/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Plato;
import DATA.ListarPlatos;
import LOGICA.ManPlato;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class Pantalla_Registro_Platos extends javax.swing.JFrame {

    ArrayList<Plato> ArrayPlato = new ArrayList<>();
    ManPlato objManPla = new ManPlato();

    /**
     * Creates new form Pantalla_Registro_Platos
     */
    public Pantalla_Registro_Platos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonActivar = new javax.swing.JButton();
        jTextFieldCombo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonProcesar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PLATOS DE COMIDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 720, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("SELECCIONE SU RESTAURANTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----NINGUNO-----", "KFC", "FOGON", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("N° Combo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jButtonActivar.setText("Activar");
        jButtonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jTextFieldCombo.setEnabled(false);
        jPanel2.add(jTextFieldCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setText("Precio");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTextFieldPrecio.setEnabled(false);
        jPanel2.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Detalles del combo agregado");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jButtonProcesar.setText("Procesar");
        jButtonProcesar.setEnabled(false);
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jTextField1.setEnabled(false);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 190, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 720, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivarActionPerformed
        // TODO add your handling code here:
        if ((this.jComboBox1.getSelectedIndex()) == 0) {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUN RESTAURANTE");
        }
        if ((this.jComboBox1.getSelectedIndex()) != 0) {
            this.jTextFieldCombo.setEnabled(true);
            this.jTextFieldPrecio.setEnabled(true);
            this.jTextField1.setEnabled(true);
            this.jButtonProcesar.setEnabled(true);
            if ((this.jComboBox1.getSelectedIndex()) == 1) {
                JOptionPane.showMessageDialog(null, "A SELECCIONADO KFC");
            }
            if ((this.jComboBox1.getSelectedIndex()) == 2) {
                JOptionPane.showMessageDialog(null, "A SELECCIONADO FOGON");
            }

        }

    }//GEN-LAST:event_jButtonActivarActionPerformed

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        // TODO add your handling code here:
        Plato objPla = new Plato();
        ListarPlatos objLisPla = new ListarPlatos();

        if (this.jTextFieldCombo.getText().isEmpty() || this.jTextFieldPrecio.getText().isEmpty() || this.jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPOS FALTANTES POR LLENAR, POR FAVOR REVISAR");
        } else {
            if (this.jComboBox1.getSelectedIndex() == 1) {
                objPla = this.objManPla.RegistrarPlato(this.jTextFieldCombo.getText(), Integer.valueOf(this.jTextFieldPrecio.getText()),
                        this.jTextField1.getText());

                this.objManPla.AñadirPlato(ArrayPlato, this.jTextFieldCombo.getText(), Integer.valueOf(this.jTextFieldPrecio.getText()),
                        this.jTextField1.getText());
//                Pantalla_Eleccion_Restaurante objPanRes = new Pantalla_Eleccion_Restaurante();
                System.out.println("PLATO REGISTRADO CON EXITO");
                try {
                    //        System.out.println(objPer.toString());
//        System.out.println(objCli.toString());
                    objLisPla.escribirPlatosKfc(objPla);
                } catch (IOException ex) {
                    Logger.getLogger(Pantalla_Registro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
//            if (this.jComboBox1.getSelectedIndex() == 2) {
//                objPla = this.objManPla.RegistrarPlato(this.jTextFieldCombo.getText(), Integer.valueOf((this.jTextFieldPrecio.getText())),
//                        this.jTextField1.getText());
//
//                this.objManPla.AñadirPlato(ArrayPlato, this.jTextFieldCombo.getText(), Integer.valueOf(this.jTextFieldPrecio.getText()),
//                        this.jTextField1.getText());
//                
////                Pantalla_Eleccion_Restaurante objPanRes = new Pantalla_Eleccion_Restaurante();
//                System.out.println("PLATO REGISTRADO CON EXITO");
//                try {
//                    //        System.out.println(objPer.toString());
////        System.out.println(objCli.toString());
//                    objLisPla.escribirPlatosFogon(objPla);
//                } catch (IOException ex) {
//                    Logger.getLogger(Pantalla_Registro.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
            
        }
    }//GEN-LAST:event_jButtonProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Registro_Platos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCombo;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
