/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Pedido;
import Clases.Plato;
import Clases.Restaurante;
import DATA.ListarPedidos;
import LOGICA.ManPlato;
import LOGICA.ManRestaurante;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jorge
 */
public class Pantalla_Eleccion_Restaurante extends javax.swing.JFrame {

    ArrayList<Plato> ArrayPlatoKfc = new ArrayList<>();
    ArrayList<Plato> ArrayPlatoFogon = new ArrayList<>();
    ManPlato objManPla = new ManPlato();
    Pedido objPed = new Pedido();
    Plato objPla = new Plato();
    int selected = -1;

    /**
     * Creates new form Pantalla_Kfc
     */
    public Pantalla_Eleccion_Restaurante() {
        initComponents();
        ArrayPlatoKfc = objManPla.ImportarCombo_Kfc(ArrayPlatoKfc);
        ArrayPlatoFogon = objManPla.ImportarCombo_Fogon(ArrayPlatoFogon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonListar = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButtonProcesar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNumMesa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCombo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalle = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTotalPagar = new javax.swing.JTextField();
        jButtonEnviarPedido = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        jLabel1.setText("BOULEVAR DEL RIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1280, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Seleccione un restaurante ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1220, 90));

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Cantidad a pedir");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jButtonProcesar.setText("Procesar");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1280, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel4.setText("DATOS DEL PEDIDO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Combo (N°)");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTextFieldCombo.setEditable(false);
        jPanel3.add(jTextFieldCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText("Cantidad");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jTextFieldCantidad.setEditable(false);
        jPanel3.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 80, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText("Detalles");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextAreaDetalle.setEditable(false);
        jTextAreaDetalle.setColumns(20);
        jTextAreaDetalle.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetalle);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 90, 200, 130));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setText("Precio Unitario");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jTextFieldPrecioUnitario.setEditable(false);
        jPanel3.add(jTextFieldPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 90, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel9.setText("Total a pagar");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jTextFieldTotalPagar.setEditable(false);
        jPanel3.add(jTextFieldTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 90, -1));

        jButtonEnviarPedido.setText("Enviar Pedido");
        jPanel3.add(jButtonEnviarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 690, 170));

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Cargar a carrito");
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1280, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        jTable1.removeAll();
        Object columnas[] = {"N° COMBO", "PRECIO COMBO", "DESCRIPCION"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        if (this.jComboBox1.getSelectedIndex() == 1) {
            for (Plato objPla : ArrayPlatoKfc) {
                String NewValor[] = {objPla.getNombre_Plato(), Integer.toString((int) objPla.getPrecio()), objPla.getDetalle()
                };
                modelo.addRow(NewValor);
            }
        }

        if (this.jComboBox1.getSelectedIndex() == 2) {
            for (Plato objPla : ArrayPlatoFogon) {
                String NewValor[] = {objPla.getNombre_Plato(), Integer.toString((int) objPla.getPrecio()), objPla.getDetalle()
                };
                modelo.addRow(NewValor);
            }
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selected = jTable1.getSelectedRow();
        this.jTextFieldCombo.setText(jTable1.getValueAt(selected, 0).toString());
        this.jTextFieldPrecioUnitario.setText(jTable1.getValueAt(selected, 1).toString());
        this.jTextAreaDetalle.setText(jTable1.getValueAt(selected, 2).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.jSpinner1.getValue().toString());
        int aux = 0;

        int Total = 0;
//        if (this.jComboBoxRest.getSelectedIndex() == 1) {

        if (valor > 0) {
            if (this.jTable1.getValueAt(0, 0).equals("Combo1")) {
                Total = Integer.valueOf(this.jTextFieldPrecioUnitario.getText()) * valor;
                aux = aux + Total;
            }
            if (this.jTable1.getValueAt(1, 0).equals("Combo2")) {
                Total = Integer.valueOf(this.jTextFieldPrecioUnitario.getText()) * valor;
            }
            if (this.jTable1.getValueAt(2, 0).equals("Combo3")) {
                Total = Integer.valueOf(this.jTextFieldPrecioUnitario.getText()) * valor;

            }

        }
//        }

        this.jTextFieldCantidad.setText(this.jSpinner1.getValue().toString());
        this.jTextFieldTotalPagar.setText(Integer.toString((int) Total));
    }//GEN-LAST:event_jButtonProcesarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarPedidoActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
//        int aux=0; 
//        int valorActu = Integer.valueOf(this.jTextFieldTotalPagar.getText());
//        
//        
//        if(JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE SU PEDIDO?", "\tALERTA DE CAMBIO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
//            JOptionPane.showMessageDialog(null, "SE ENVIO SU PEDIDO CON EXITO");
//            this.jButtonProcesar.setEnabled(false);
//            
//            
////            ListarPedidos lisPe = new ListarPedidos();
////            objPla = this.objManPla.NuevoPlato(this.jTable1.getValueAt(0, 0), this.jTable1.getValueAt(0, 1), 
////                    this.jTable1.getValueAt(0, 2), objPed);
////            
////            this.objManPla.AgregarPlato(ArrayPlatoKfc, this.jTable1.getValueAt(0, 0), this.jTable1.getValueAt(0, 1), 
////                    this.jTable1.getValueAt(0, 2), objPed);  
//            
//            JOptionPane.showMessageDialog(null, "ORDEN ENVIADA CON EXITO");
////        try {
////            //        System.out.println(objPer.toString());
//////        System.out.println(objCli.toString());
////            lisPe.escribirPedidos(objPla);
////        } catch (IOException ex) {
////            Logger.getLogger(Pantalla_Registro.class.getName()).log(Level.SEVERE, null, ex);
////        }
//            
//            Pantalla_Factura2 objPanFac = new Pantalla_Factura2();
//            objPanFac.setVisible(true);
//            dispose();
//        } else {
//            JOptionPane.showMessageDialog(null, "SELECCIONE OTROS PEDIDOS");
//            this.jButtonProcesar.setEnabled(true);
//            jButtonProcesarActionPerformed(evt);
//            aux = aux + valorActu;
//            this.jTextFieldTotalPagar.setText(Integer.toString(aux));
//            System.out.println("Valor actual "+valorActu);
//            System.out.println("Valor nuevo "+aux);
//        }
//        
        
           
        
=======
        int aux = 0;
        int valorActu = Integer.valueOf(this.jTextFieldTotalPagar.getText());

        if (JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE SU PEDIDO?", "\tALERTA DE CAMBIO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "SE ENVIO SU PEDIDO CON EXITO");
            this.jButtonProcesar.setEnabled(false);

            ListarPedidos lisPe = new ListarPedidos();
            objPla = this.objManPla.NuevoPlato(this.jTable1.getValueAt(0, 0).toString(), Double.parseDouble(this.jTable1.getValueAt(0, 1).toString()),
                    this.jTable1.getValueAt(0, 2).toString(), objPed);

            this.objManPla.AgregarPlato(ArrayPlatoKfc, this.jTable1.getValueAt(0, 0).toString(), Double.parseDouble(this.jTable1.getValueAt(0, 1).toString()),
                    this.jTable1.getValueAt(0, 2).toString(), objPed);

            JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CON EXITO");
            try {
                //        System.out.println(objPer.toString());
//        System.out.println(objCli.toString());
                lisPe.escribirPedidos(objPla);
            } catch (IOException ex) {
                Logger.getLogger(Pantalla_Registro.class.getName()).log(Level.SEVERE, null, ex);
            }

            Pantalla_Factura2 objPanFac = new Pantalla_Factura2();
            objPanFac.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONE OTROS PEDIDOS");
            this.jButtonProcesar.setEnabled(true);
            jButtonProcesarActionPerformed(evt);
            aux = aux + valorActu;
            this.jTextFieldTotalPagar.setText(Integer.toString(aux));
            System.out.println("Valor actual " + valorActu);
            System.out.println("Valor nuevo " + aux);
        }


>>>>>>> 03dae13a3ccf12782e4961c4fdb46ca3316b0b49
    }//GEN-LAST:event_jButtonEnviarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Eleccion_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Eleccion_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Eleccion_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Eleccion_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Eleccion_Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarPedido;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaDetalle;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCombo;
    private javax.swing.JTextField jTextFieldNumMesa;
    private javax.swing.JTextField jTextFieldPrecioUnitario;
    private javax.swing.JTextField jTextFieldTotalPagar;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
